DISTRO = precise trusty

.PHONY: ruby all $(DISTRO)

ifndef SHA
	SHA:=$(shell git rev-parse HEAD)
else
	echo Building SHA=$(SHA)
endif
ifndef OUTDIR
  OUTDIR = $(realpath $(dir $(lastword $(MAKEFILE_LIST))))/artifacts
endif

all: ruby

ruby: $(DISTRO)

$(DISTRO): 
	./ruby_build -d $@ $(shell cat build.version) --output $(OUTDIR)/$@
