#!/bin/bash

function try {
  echo "$@"
  if ! "$@" &> log; then
    echo "*** '$@' FAILED" 1>&2
    cat log 1>&2
    exit 1
  fi
}

cd "$(dirname "$0")/.."

branch_name="$1"
commit="$(git rev-parse --short HEAD)"

perl -pi -e "s/development/$branch_name $commit/" version.h

try autoconf
try ./configure --prefix=/data/ruby --disable-install-doc
try make -j 4
try make install
