use crate::asm::*;
use crate::asm::x86_64::*;
use crate::codegen::split_patch_point;
use crate::stats::{CompileError, trace_compile_phase};
use crate::virtualmem::CodePtr;
use crate::cruby::*;
use crate::backend::lir::*;
use crate::cast::*;
use crate::options::asm_dump;

// Use the x86 register type for this platform
pub type Reg = X86Reg;

// Callee-saved registers
pub const CFP: Opnd = Opnd::Reg(R13_REG);
pub const EC: Opnd = Opnd::Reg(R12_REG);
pub const SP: Opnd = Opnd::Reg(RBX_REG);

// C argument registers on this platform
pub const C_ARG_OPNDS: [Opnd; 6] = [
    Opnd::Reg(RDI_REG),
    Opnd::Reg(RSI_REG),
    Opnd::Reg(RDX_REG),
    Opnd::Reg(RCX_REG),
    Opnd::Reg(R8_REG),
    Opnd::Reg(R9_REG)
];
pub const C_ARG_REGREGS: [Reg; 6] = [RDI_REG, RSI_REG, RDX_REG, RCX_REG, R8_REG, R9_REG];

// C return value register on this platform
pub const C_RET_REG: Reg = RAX_REG;
pub const C_RET_OPND: Opnd = Opnd::Reg(RAX_REG);
pub const NATIVE_STACK_PTR: Opnd = Opnd::Reg(RSP_REG);
pub const NATIVE_BASE_PTR: Opnd = Opnd::Reg(RBP_REG);

impl CodeBlock {
    // The number of bytes that are generated by jmp_ptr
    pub fn jmp_ptr_bytes(&self) -> usize { 5 }
}

/// Map Opnd to X86Opnd
impl From<Opnd> for X86Opnd {
    fn from(opnd: Opnd) -> Self {
        match opnd {
            Opnd::VReg{..} => panic!("VReg operand made it past register allocation"),

            Opnd::UImm(val) => uimm_opnd(val),
            Opnd::Imm(val) => imm_opnd(val),
            Opnd::Value(VALUE(uimm)) => uimm_opnd(uimm as u64),

            // General-purpose register
            Opnd::Reg(reg) => X86Opnd::Reg(reg),

            Opnd::None => panic!(
                "Attempted to lower an Opnd::None. This often happens when an out operand was not allocated for an instruction because the output of the instruction was not used. Please ensure you are using the output."
            ),
        }
    }
}

/// Also implement going from a reference to an operand for convenience.
impl From<&Opnd> for X86Opnd {
    fn from(opnd: &Opnd) -> Self {
        X86Opnd::from(*opnd)
    }
}

/// Map Mem to X86Opnd
impl From<Mem> for X86Opnd {
    fn from(mem: Mem) -> Self {
        let Mem { base, disp, num_bits } = mem;
        let Opnd::Reg(base) = base else {
            panic!("attempted to lower a Mem with a non-register base: {base:?}")
        };
        mem_opnd(num_bits, X86Opnd::Reg(base.with_num_bits(64)), disp)
    }
}

impl From<&Mem> for X86Opnd {
    fn from(mem: &Mem) -> Self {
        X86Opnd::from(*mem)
    }
}

/// List of registers that can be used for register allocation.
/// This has the same number of registers for x86_64 and arm64.
/// SCRATCH0_OPND is excluded.
pub const ALLOC_REGS: &[Reg] = &[
    RDI_REG,
    RSI_REG,
    RDX_REG,
    RCX_REG,
    R8_REG,
    R9_REG,
    RAX_REG,
];

/// Special scratch register for intermediate processing. It should be used only by
/// [`Assembler::x86_scratch_split`] or [`Assembler::new_with_scratch_reg`].
const SCRATCH0_OPND: Opnd = Opnd::Reg(R11_REG);
const SCRATCH1_OPND: Opnd = Opnd::Reg(R10_REG);

/// A scratch register available for use by resolve_ssa to break register copy cycles.
/// Must not overlap with ALLOC_REGS or other preserved registers.
pub const SCRATCH_REG: Reg = R11_REG;

impl Assembler {
    // This keeps frame growth below the +/-4096-byte displacement range we rely
    // on for common stack-slot accesses on x86_64.
    const MAX_FRAME_STACK_SLOTS: usize = 2048;

    /// Return an Assembler with scratch registers disabled in the backend, and a scratch register.
    pub fn new_with_scratch_reg() -> (Self, Opnd) {
        (Self::new_with_accept_scratch_reg(true), SCRATCH0_OPND)
    }

    /// Return true if opnd contains a scratch reg
    pub fn has_scratch_reg(opnd: Opnd) -> bool {
        Self::has_reg(opnd, SCRATCH0_OPND.unwrap_reg())
    }

    /// Get the list of registers from which we can allocate on this platform
    pub fn get_alloc_regs() -> Vec<Reg> {
        ALLOC_REGS.to_vec()
    }

    /// Get a list of all of the caller-save registers
    pub fn get_caller_save_regs() -> Vec<Reg> {
        vec![RAX_REG, RCX_REG, RDX_REG, RSI_REG, RDI_REG, R8_REG, R9_REG, R10_REG, R11_REG]
    }

    /// How many bytes a call and a bare bones [Self::frame_setup] would change native SP
    pub fn frame_size() -> i32 {
        0x10
    }

    // These are the callee-saved registers in the x86-64 SysV ABI
    // RBX, RSP, RBP, and R12-R15

    /// Split IR instructions for the x86 platform
    fn x86_split(mut self) -> Assembler
    {
        let mut asm_local = Assembler::new_with_asm(&self);
        let asm = &mut asm_local;
        let mut iterator = self.instruction_iterator();

        while let Some((_index, mut insn)) = iterator.next(asm) {
            let is_load = matches!(insn, Insn::Load { .. } | Insn::LoadInto { .. });
            let is_jump = insn.is_jump();

            if !is_jump {
                insn.for_each_operand_mut(|opnd| {
                    // Lower Opnd::Value to Opnd::VReg or Opnd::UImm
                    if let Opnd::Value(value) = opnd {
                        // If the value is a special constant, and it fits in 32 bits,
                        // then we're going to output this as just an immediate
                        if value.special_const_p() {
                            if imm_num_bits(value.as_i64()) > 32 {
                                *opnd = asm.load(*opnd);
                            } else {
                                *opnd = Opnd::UImm(value.as_u64());
                            }
                            // If we're already loading it, don't load it again
                            // If it's a jump, then we want to let parallel move
                            // take care of the block params (otherwise we end up
                            // with loads between jump instructions)
                        } else if !is_load {
                            *opnd = asm.load(*opnd);
                        }
                    }
                });
            }

            // We are replacing instructions here so we know they are already
            // being used. It is okay not to use their output here.
            #[allow(unused_must_use)]
            match &mut insn {
                Insn::Add { .. } |
                Insn::Sub { .. } |
                Insn::Mul { .. } |
                Insn::And { .. } |
                Insn::Or { .. } |
                Insn::Xor { .. } => {
                    asm.push_insn(insn);
                },
                Insn::Cmp { left, right } => {
                    // Replace `cmp REG, 0` (4 bytes) with `test REG, REG` (3 bytes)
                    // when next IR is `je`, `jne`, `csel_e`, or `csel_ne`
                    match (&left, &right, iterator.peek().map(|(_, insn)| insn)) {
                        (Opnd::VReg { .. },
                         Opnd::UImm(0) | Opnd::Imm(0),
                         Some(Insn::Je(_) | Insn::Jne(_) | Insn::CSelE { .. } | Insn::CSelNE { .. })) => {
                            asm.push_insn(Insn::Test { left: *left, right: *left });
                        }
                        _ => {
                            // The left operand needs to be a register
                            if let Opnd::UImm(_) | Opnd::Imm(_) = left {
                                *left = asm.load(*left);
                            }
                            asm.push_insn(insn);
                        }
                    }
                },
                Insn::Test { left, .. } => {
                    // The first operand can't be an immediate value
                    if let Opnd::UImm(_) | Opnd::Imm(_) = left {
                        *left = asm.load(*left);
                    }
                    asm.push_insn(insn);
                },
                // These instructions modify their input operand in-place, so we
                // need to load the input value to preserve it
                Insn::LShift { opnd, .. } |
                Insn::RShift { opnd, .. } |
                Insn::URShift { opnd, .. } => {
                    *opnd = asm.load(*opnd);
                    asm.push_insn(insn);
                },
                Insn::CSelZ { truthy, falsy, .. } |
                Insn::CSelNZ { truthy, falsy, .. } |
                Insn::CSelE { truthy, falsy, .. } |
                Insn::CSelNE { truthy, falsy, .. } |
                Insn::CSelL { truthy, falsy, .. } |
                Insn::CSelLE { truthy, falsy, .. } |
                Insn::CSelG { truthy, falsy, .. } |
                Insn::CSelGE { truthy, falsy, .. } => {
                    match *truthy {
                        // If we have an instruction output whose live range
                        // spans beyond this instruction, we have to load it.
                        Opnd::VReg { idx: _, .. } => {
                            if true /* conservatively assume vreg outlives insn */ {
                                *truthy = asm.load(*truthy);
                            }
                        },
                        Opnd::UImm(_) | Opnd::Imm(_) => {
                            *truthy = asm.load(*truthy);
                        },
                        // Opnd::Value could have already been split
                        Opnd::Value(_) if !matches!(truthy, Opnd::VReg { .. }) => {
                            *truthy = asm.load(*truthy);
                        },
                        _ => {}
                    }

                    match falsy {
                        Opnd::UImm(_) | Opnd::Imm(_) => {
                            *falsy = asm.load(*falsy);
                        },
                        _ => {}
                    }

                    asm.push_insn(insn);
                },
                Insn::Not { opnd, .. } => {
                    match *opnd {
                        // If we have an instruction output whose live range
                        // spans beyond this instruction, we have to load it.
                        Opnd::VReg { idx: _, .. } => {
                            if true /* conservatively assume vreg outlives insn */ {
                                *opnd = asm.load(*opnd);
                            }
                        },
                        // We have to load register operands to avoid corrupting them.
                        Opnd::Reg(_) => {
                            *opnd = asm.load(*opnd);
                        },
                        // Otherwise we can just reuse the existing operand.
                        _ => {},
                    };
                    asm.push_insn(insn);
                },
                Insn::CCall { .. } => {
                    // CCall argument setup is handled by handle_caller_saved_regs.
                    asm.push_insn(insn);
                },
                Insn::Lea { .. } => {
                    asm.push_insn(insn);
                },
                _ => {
                    asm.push_insn(insn);
                }
            }
        }

        asm_local
    }

    /// Split instructions using scratch registers. To maximize the use of the register pool
    /// for VRegs, most splits should happen in [`Self::x86_split`]. However, some instructions
    /// need to be split with registers after `alloc_regs`, e.g. for `compile_exits`, so
    /// this splits them and uses scratch registers for it.
    pub fn x86_scratch_split(self) -> Assembler {
        /// For some instructions, we want to be able to lower a 64-bit operand
        /// without requiring more registers to be available in the register
        /// allocator. So we just use the SCRATCH0_OPND register temporarily to hold
        /// the value before we immediately use it.
        fn split_64bit_immediate(asm: &mut Assembler, opnd: Opnd, scratch_opnd: Opnd) -> Opnd {
            match opnd {
                Opnd::Imm(value) => {
                    // 32-bit values will be sign-extended
                    if imm_num_bits(value) > 32 {
                        asm.mov(scratch_opnd, opnd);
                        scratch_opnd
                    } else {
                        opnd
                    }
                },
                Opnd::UImm(value) => {
                    // 32-bit values will be sign-extended
                    if imm_num_bits(value as i64) > 32 {
                        asm.mov(scratch_opnd, opnd);
                        scratch_opnd
                    } else {
                        Opnd::Imm(value as i64)
                    }
                },
                _ => opnd
            }
        }

        /// Whether two operands name the same physical register, ignoring width.
        fn same_reg(a: Opnd, b: Opnd) -> bool {
            matches!((a, b), (Opnd::Reg(a), Opnd::Reg(b)) if a.reg_no == b.reg_no)
        }

        /// A VReg that survived register allocation was spilled: reload it into a scratch
        /// register. Anything else is already a location the emitter can use.
        fn reload(asm: &mut Assembler, opnd: &mut Opnd, scratch_opnd: Opnd) {
            let Opnd::VReg { num_bits, .. } = *opnd else { return };
            let slot = asm.spill_slot(*opnd);
            let scratch = scratch_opnd.with_num_bits(num_bits);
            asm.load_mem_into(scratch, slot);
            *opnd = scratch;
        }

        /// Redirect a spilled output into a scratch register, and return the frame slot the
        /// result has to be written back to.
        fn spill_out(asm: &Assembler, out: &mut Opnd, scratch_opnd: Opnd) -> Option<Mem> {
            let Opnd::VReg { num_bits, .. } = *out else { return None };
            let slot = asm.spill_slot(*out);
            *out = scratch_opnd.with_num_bits(num_bits);
            Some(slot)
        }

        /// Make a memory location emittable: its base has to be in a real register.
        fn lower_mem(asm: &mut Assembler, mem: Mem, scratch_opnd: Opnd) -> Mem {
            let mut mem = mem;
            reload(asm, &mut mem.base, scratch_opnd.with_num_bits(64));
            mem
        }

        /// Normalize the value side of a store: `mov [mem], imm` can't take a 64-bit
        /// immediate or a GC'd value, so those go through a scratch register.
        fn split_store_src(asm: &mut Assembler, src: Opnd, num_bits: u8, scratch_opnd: Opnd) -> Opnd {
            match src {
                Opnd::Reg(_) => src,
                Opnd::Imm(imm) => {
                    // For 64 bit destinations, 32-bit values will be sign-extended
                    if num_bits == 64 && imm_num_bits(imm) > 32 {
                        asm.mov(scratch_opnd, src);
                        scratch_opnd
                    } else if uimm_num_bits(imm as u64) <= num_bits {
                        // If the bit string is short enough for the destination, use the unsigned representation.
                        // Note that 64-bit and negative values are ruled out.
                        Opnd::UImm(imm as u64)
                    } else {
                        src
                    }
                }
                Opnd::UImm(imm) => {
                    // For 64 bit destinations, 32-bit values will be sign-extended
                    if num_bits == 64 && imm_num_bits(imm as i64) > 32 {
                        asm.mov(scratch_opnd, src);
                        scratch_opnd
                    } else {
                        src
                    }
                }
                Opnd::Value(_) => {
                    asm.load_into(scratch_opnd, src);
                    scratch_opnd
                }
                src @ (Opnd::None | Opnd::VReg { .. }) => panic!("Unexpected source operand during x86_scratch_split: {src:?}"),
            }
        }

        /// Move `src` into `dest`, where `dest` may be a spilled VReg. Skip it if dest == src.
        fn mov_to(asm: &mut Assembler, dest: Opnd, src: Opnd, scratch_opnd: Opnd) {
            if let Opnd::VReg { .. } = dest {
                let slot = asm.spill_slot(dest);
                let src = split_store_src(asm, src, slot.num_bits, scratch_opnd);
                asm.store(slot, src);
            } else if dest != src {
                asm.mov(dest, src);
            }
        }

        /// Lower a CPushPair operand into something push can encode: a register or a
        /// zero immediate. Anything else is loaded into scratch_opnd.
        fn split_push_operand(asm: &mut Assembler, opnd: Opnd, scratch_opnd: Opnd) -> Opnd {
            match opnd {
                Opnd::Reg(_) | Opnd::UImm(0) | Opnd::Imm(0) => opnd,
                Opnd::VReg { .. } => {
                    let mut opnd = opnd;
                    reload(asm, &mut opnd, scratch_opnd);
                    opnd
                }
                _ => {
                    asm.load_into(scratch_opnd, opnd);
                    scratch_opnd
                }
            }
        }

        let mut asm_local = Assembler::new_with_asm_without_blocks(&self);
        asm_local.accept_scratch_reg = true;

        // Create one giant block to linearize everything into
        asm_local.new_block_without_id("linearized");

        let asm = &mut asm_local;

        // Get linearized instructions with branch parameters expanded into ParallelMov
        let linearized_insns = self.linearize_instructions();

        for insn in linearized_insns.iter() {
            let mut insn = insn.clone();
            match &mut insn {
                Insn::Add { left, right, out } |
                Insn::Sub { left, right, out } |
                Insn::And { left, right, out } |
                Insn::Or  { left, right, out } |
                Insn::Xor { left, right, out } => {
                    // Lower into x86's two-operand form: the instruction reads and writes
                    // `left`, which register allocation has already made equal to `out`
                    // where it could. SCRATCH0 stands in for a spilled `out` (and hence
                    // `left`), SCRATCH1 for a spilled `right`.
                    reload(asm, right, SCRATCH1_OPND);
                    let mut left_opnd = *left;
                    let out_slot = spill_out(asm, out, SCRATCH0_OPND);

                    // `OP out, right` clobbers out, so right must not live there.
                    if same_reg(*right, *out) {
                        asm.mov(SCRATCH1_OPND, *right);
                        *right = SCRATCH1_OPND;
                    }
                    *right = split_64bit_immediate(asm, *right, SCRATCH1_OPND);

                    // Get left into out, then operate in place.
                    reload(asm, &mut left_opnd, *out);
                    if *out != left_opnd {
                        asm.mov(*out, left_opnd);
                    }
                    *left = *out;

                    let out_opnd = *out;
                    asm.push_insn(insn);

                    if let Some(out_slot) = out_slot {
                        asm.store(out_slot, out_opnd);
                    }
                }
                Insn::Mul { left, right, out } => {
                    // imul writes its result into `left`, which must be a register.
                    reload(asm, left, SCRATCH0_OPND);
                    reload(asm, right, SCRATCH1_OPND);
                    *right = split_64bit_immediate(asm, *right, SCRATCH1_OPND);
                    let out_slot = spill_out(asm, out, SCRATCH0_OPND);

                    let (out_opnd, left_opnd) = (*out, *left);
                    asm.push_insn(insn);
                    if out_opnd != left_opnd {
                        asm.mov(out_opnd, left_opnd);
                    }

                    if let Some(out_slot) = out_slot {
                        asm.store(out_slot, out_opnd);
                    }
                }
                Insn::Not { opnd, out } |
                Insn::LShift { opnd, out, .. } |
                Insn::RShift { opnd, out, .. } |
                Insn::URShift { opnd, out, .. } => {
                    // These modify `opnd` in place; x86_split has already given them a
                    // freshly loaded value, so clobbering it is fine. The result is then
                    // copied into out.
                    reload(asm, opnd, SCRATCH0_OPND);
                    let out_slot = spill_out(asm, out, SCRATCH0_OPND);
                    let (out_opnd, in_opnd) = (*out, *opnd);

                    asm.push_insn(insn);

                    if out_opnd != in_opnd {
                        asm.mov(out_opnd, in_opnd);
                    }
                    if let Some(out_slot) = out_slot {
                        asm.store(out_slot, out_opnd);
                    }
                }
                Insn::Test { left, right } |
                Insn::Cmp { left, right } => {
                    reload(asm, left, SCRATCH0_OPND);
                    reload(asm, right, SCRATCH1_OPND);

                    let num_bits = match right {
                        Opnd::Imm(value) => Some(imm_num_bits(*value)),
                        Opnd::UImm(value) => Some(uimm_num_bits(*value)),
                        _ => None
                    };

                    // If the immediate is less than 64 bits (like 32, 16, 8), and the operand
                    // sizes match, then we can represent it as an immediate in the instruction
                    // without moving it to a register first.
                    // IOW, 64 bit immediates must always be moved to a register
                    // before comparisons, where other sizes may be encoded
                    // directly in the instruction.
                    let use_imm = num_bits.is_some() && left.num_bits() == num_bits && num_bits.unwrap() < 64;
                    if !use_imm {
                        *right = split_64bit_immediate(asm, *right, SCRATCH1_OPND);
                    }
                    asm.push_insn(insn);
                }
                // For compile_exits, support splitting simple C arguments here
                Insn::CCall { data } if !data.opnds.is_empty() => {
                    for (i, opnd) in data.opnds.iter().enumerate() {
                        let mut opnd = *opnd;
                        reload(asm, &mut opnd, C_ARG_OPNDS[i]);
                        asm.load_into(C_ARG_OPNDS[i], opnd);
                    }
                    data.opnds = vec![];
                    asm.push_insn(insn);
                }
                // For compile_exits, support splitting simple return values here
                Insn::CRet(opnd) => {
                    reload(asm, opnd, SCRATCH0_OPND);
                    asm.push_insn(insn);
                }
                Insn::CSelZ  { truthy, falsy, out } |
                Insn::CSelNZ { truthy, falsy, out } |
                Insn::CSelE  { truthy, falsy, out } |
                Insn::CSelNE { truthy, falsy, out } |
                Insn::CSelL  { truthy, falsy, out } |
                Insn::CSelLE { truthy, falsy, out } |
                Insn::CSelG  { truthy, falsy, out } |
                Insn::CSelGE { truthy, falsy, out } => {
                    // emit_csel opens with `mov out, truthy`, so a spilled truthy can share
                    // SCRATCH1 with a spilled out and save the copy. SCRATCH0 is left free
                    // for emit_csel to stage falsy when it aliases out.
                    reload(asm, falsy, SCRATCH0_OPND);
                    reload(asm, truthy, SCRATCH1_OPND);
                    let out_slot = spill_out(asm, out, SCRATCH1_OPND);

                    let out_opnd = *out;
                    asm.push_insn(insn);

                    if let Some(out_slot) = out_slot {
                        asm.store(out_slot, out_opnd);
                    }
                }
                Insn::Lea { mem, out } => {
                    *mem = lower_mem(asm, *mem, SCRATCH1_OPND);
                    let out_slot = spill_out(asm, out, SCRATCH0_OPND);

                    let out_opnd = *out;
                    asm.push_insn(insn);

                    if let Some(out_slot) = out_slot {
                        asm.store(out_slot, out_opnd);
                    }
                }
                Insn::LeaJumpTarget { target, out } => {
                    if let Target::Label(_) = target {
                        asm.push_insn(Insn::LeaJumpTarget { out: SCRATCH0_OPND, target: target.clone() });
                        mov_to(asm, *out, SCRATCH0_OPND, SCRATCH1_OPND);
                    }
                }
                Insn::LoadMem { mem, out } |
                Insn::LoadSExt { mem, out } => {
                    *mem = lower_mem(asm, *mem, SCRATCH0_OPND);
                    let out_slot = spill_out(asm, out, SCRATCH1_OPND);

                    let out_opnd = *out;
                    asm.push_insn(insn);

                    if let Some(out_slot) = out_slot {
                        asm.store(out_slot, out_opnd);
                    }
                }
                Insn::LoadMemInto { mem, .. } => {
                    *mem = lower_mem(asm, *mem, SCRATCH0_OPND);
                    asm.push_insn(insn);
                }
                Insn::Load { out, opnd } |
                Insn::LoadInto { dest: out, opnd } => {
                    reload(asm, opnd, SCRATCH0_OPND);
                    let out_slot = spill_out(asm, out, SCRATCH1_OPND);

                    let out_opnd = *out;
                    asm.push_insn(insn);

                    if let Some(out_slot) = out_slot {
                        asm.store(out_slot, out_opnd);
                    }
                }
                Insn::IncrCounter { mem, .. } => {
                    *mem = lower_mem(asm, *mem, SCRATCH0_OPND);
                    asm.push_insn(insn);
                }
                &mut Insn::Mov { dest, src } => {
                    // Mov is what the parallel-move sequentializer emits, and it keeps a
                    // value live in SCRATCH_REG (== SCRATCH0) across the copies it uses to
                    // break a cycle. So lower Mov without ever touching SCRATCH0.
                    debug_assert_eq!(SCRATCH_REG, SCRATCH0_OPND.unwrap_reg());
                    let mut src = src;
                    reload(asm, &mut src, SCRATCH1_OPND);
                    mov_to(asm, dest, src, SCRATCH1_OPND);
                }
                Insn::Store { mem, src } => {
                    reload(asm, src, SCRATCH0_OPND);
                    *mem = lower_mem(asm, *mem, SCRATCH1_OPND);
                    *src = split_store_src(asm, *src, mem.num_bits, SCRATCH0_OPND);
                    asm.push_insn(insn);
                }
                Insn::CPushPair(opnd0, opnd1) => {
                    if let Some(opnd0) = opnd0 {
                        *opnd0 = split_push_operand(asm, *opnd0, SCRATCH0_OPND);
                    }
                    *opnd1 = split_push_operand(asm, *opnd1, SCRATCH1_OPND);
                    asm.push_insn(insn);
                }
                &mut Insn::PatchPoint(ref data) => {
                    split_patch_point(asm, &data.target, data.invariant, data.version);
                }
                _ => {
                    asm.push_insn(insn);
                }
            }
        }

        asm_local
    }

    /// Emit platform-specific machine code
    pub fn x86_emit(&mut self, cb: &mut CodeBlock) -> Result<Vec<CodePtr>, CompileError> {
        /// Emit `out = cond ? truthy : falsy` as `mov out, truthy` followed by a
        /// conditional move of `falsy` under the negated condition.
        fn emit_csel(
            cb: &mut CodeBlock,
            truthy: Opnd,
            falsy: Opnd,
            out: Opnd,
            cmov_neg: fn(&mut CodeBlock, X86Opnd, X86Opnd)){

            // Assert that output is a register
            let out_reg = out.unwrap_reg();

            /// Check if an operand is the given register.
            fn aliases_reg(opnd: &Opnd, reg: Reg) -> bool {
                matches!(opnd, Opnd::Reg(r) if r.reg_no == reg.reg_no)
            }

            // If out aliases falsy, we must load falsy into the scratch
            // register first to avoid clobbering it with the truthy mov.
            if aliases_reg(&falsy, out_reg) {
                mov(cb, SCRATCH0_OPND.into(), falsy.into());
                if out != truthy {
                    mov(cb, out.into(), truthy.into());
                }
                cmov_neg(cb, out.into(), SCRATCH0_OPND.into());
            } else {
                if out != truthy {
                    mov(cb, out.into(), truthy.into());
                }
                cmov_neg(cb, out.into(), falsy.into());
            }
        }

        fn emit_load_gc_value(cb: &mut CodeBlock, gc_offsets: &mut Vec<CodePtr>, dest_reg: X86Opnd, value: VALUE) {
            // Using movabs because mov might write value in 32 bits
            movabs(cb, dest_reg, value.0 as _);
            // The pointer immediate is encoded as the last part of the mov written out
            let ptr_offset = cb.get_write_ptr().sub_bytes(SIZEOF_VALUE);
            gc_offsets.push(ptr_offset);
        }

        /// Fill nops until a jump written at `last_patch_pos` can no longer reach
        /// past the current write position.
        fn emit_pad_after_patch_point(cb: &mut CodeBlock, last_patch_pos: Option<usize>) {
            let Some(last_patch_pos) = last_patch_pos else { return };
            let code_size = cb.get_write_pos().saturating_sub(last_patch_pos);
            if code_size < cb.jmp_ptr_bytes() {
                nop(cb, (cb.jmp_ptr_bytes() - code_size) as u32);
            }
        }

        // List of GC offsets
        let mut gc_offsets: Vec<CodePtr> = Vec::new();

        // Buffered list of PosMarker callbacks to fire if codegen is successful
        let mut pos_markers: Vec<(usize, CodePtr)> = vec![];

        // The write_pos for the last Insn::PatchPoint, if any
        let mut last_patch_pos: Option<usize> = None;

        // For each instruction
        let mut insn_idx: usize = 0;
        assert_eq!(self.basic_blocks.len(), 1, "Assembler should be linearized into a single block before arm64_emit");
        let insns = &self.basic_blocks[0].insns;

        while let Some(insn) = insns.get(insn_idx) {
            match insn {
                Insn::Comment(text) => {
                    cb.add_comment(text);
                },

                // Write the label at the current position
                Insn::Label(target) => {
                    cb.write_label(target.unwrap_label());
                },

                // Report back the current position in the generated code
                Insn::PosMarker(..) => {
                    pos_markers.push((insn_idx, cb.get_write_ptr()));
                },
                Insn::PosMarkerAtBlockEnd(..) => {
                    unreachable!("PosMarkerAtBlockEnd should have been lowered by linearize_instructions");
                },

                Insn::BakeString(text) => {
                    for byte in text.as_bytes() {
                        cb.write_byte(*byte);
                    }

                    // Add a null-terminator byte for safety (in case we pass
                    // this to C code)
                    cb.write_byte(0);
                },

                // Set up RBP as frame pointer work with unwinding
                // (e.g. with Linux `perf record --call-graph fp`)
                // and to allow push and pops in the function.
                &Insn::FrameSetup { preserved, mut slot_count } => {
                    // Bump slot_count for alignment if necessary
                    const { assert!(SIZEOF_VALUE == 8, "alignment logic relies on SIZEOF_VALUE == 8"); }
                    let total_slots = 2 /* rbp and return address*/ + slot_count + preserved.len();
                    if total_slots % 2 == 1 {
                        slot_count += 1;
                    }
                    push(cb, RBP);
                    mov(cb, RBP, RSP);
                    for reg in preserved {
                        push(cb, reg.into());
                    }
                    if slot_count > 0 {
                        sub(cb, RSP, uimm_opnd((slot_count * SIZEOF_VALUE) as u64));
                    }
                }
                &Insn::FrameTeardown { preserved } => {
                    let mut preserved_offset = -8;
                    for reg in preserved {
                        mov(cb, reg.into(), mem_opnd(64, RBP, preserved_offset));
                        preserved_offset -= 8;
                    }
                    mov(cb, RSP, RBP);
                    pop(cb, RBP);
                }

                Insn::Add { left, right, .. } => {
                    add(cb, left.into(), right.into());
                },

                Insn::Sub { left, right, .. } => {
                    sub(cb, left.into(), right.into());
                },

                Insn::Mul { left, right, .. } => {
                    imul(cb, left.into(), right.into());
                },

                Insn::And { left, right, .. } => {
                    and(cb, left.into(), right.into());
                },

                Insn::Or { left, right, .. } => {
                    or(cb, left.into(), right.into());
                },

                Insn::Xor { left, right, .. } => {
                    xor(cb, left.into(), right.into());
                },

                Insn::Not { opnd, .. } => {
                    not(cb, opnd.into());
                },

                Insn::LShift { opnd, shift , ..} => {
                    shl(cb, opnd.into(), shift.into())
                },

                Insn::RShift { opnd, shift , ..} => {
                    sar(cb, opnd.into(), shift.into())
                },

                Insn::URShift { opnd, shift, .. } => {
                    shr(cb, opnd.into(), shift.into())
                },

                // This assumes only load instructions can contain references to GC'd Value operands
                Insn::Load { opnd, out } |
                Insn::LoadInto { dest: out, opnd } => {
                    match opnd {
                        Opnd::Value(val) if val.heap_object_p() => {
                            emit_load_gc_value(cb, &mut gc_offsets, out.into(), *val);
                        }
                        _ => mov(cb, out.into(), opnd.into())
                    }
                },

                Insn::LoadMem { mem, out } |
                Insn::LoadMemInto { dest: out, mem } => {
                    mov(cb, out.into(), mem.into());
                },

                Insn::LoadSExt { mem, out } => {
                    movsx(cb, out.into(), mem.into());
                },

                Insn::Store { mem, src } => {
                    mov(cb, mem.into(), src.into());
                },

                Insn::Mov { dest, src } => {
                    mov(cb, dest.into(), src.into());
                },

                // Load effective address
                Insn::Lea { mem, out } => {
                    lea(cb, out.into(), mem.into());
                },

                // Load address of jump target
                Insn::LeaJumpTarget { target, out } => {
                    if let Target::Label(label) = target {
                        let out = *out;
                        // Set output to the raw address of the label
                        cb.label_ref(*label, 7, move |cb, src_addr, dst_addr| {
                            let disp = dst_addr - src_addr;
                            lea(cb, out.into(), mem_opnd(8, RIP, disp.try_into().unwrap()));
                            Ok(())
                        });
                    } else {
                        // Set output to the jump target's raw address
                        let target_code = target.unwrap_code_ptr();
                        let target_addr = target_code.raw_addr(cb).as_u64();
                        // Constant encoded length important for patching
                        movabs(cb, out.into(), target_addr);
                    }
                },

                // Push and pop to/from the C stack
                Insn::CPush(opnd) => {
                    push(cb, opnd.into());
                },
                Insn::CPushPair(opnd0, opnd1) => {
                    match opnd0 {
                        Some(opnd0) => push(cb, opnd0.into()),
                        // With no first operand, push 0 to keep the pair-sized
                        // area, consistent with survivor padding.
                        None => push(cb, uimm_opnd(0)),
                    }
                    push(cb, opnd1.into());
                },
                Insn::CPop { out } => {
                    pop(cb, out.into());
                },
                Insn::CPopInto(opnd) => {
                    pop(cb, opnd.into());
                },
                Insn::CPopPairInto(opnd0, opnd1) => {
                    pop(cb, opnd0.into());
                    pop(cb, opnd1.into());
                },

                // C function call
                Insn::CCall { data, .. } => {
                    let fptr = &data.fptr;
                    match fptr {
                        Opnd::UImm(fptr) => {
                            call_ptr(cb, RAX, *fptr as *const u8);
                        }
                        Opnd::Reg(_) => {
                            call(cb, fptr.into());
                        }
                        _ => unreachable!("unsupported ccall fptr: {fptr:?}")
                    }
                },

                Insn::CRet(opnd) => {
                    // TODO: bias allocation towards return register
                    if *opnd != Opnd::Reg(C_RET_REG) {
                        mov(cb, RAX, opnd.into());
                    }

                    ret(cb);
                },

                // Compare
                Insn::Cmp { left, right } => {
                    cmp(cb, left.into(), right.into());
                }

                // Test and set flags
                Insn::Test { left, right } => {
                    test(cb, left.into(), right.into());
                }

                Insn::JmpOpnd(opnd) => {
                    jmp_rm(cb, opnd.into());
                }

                // Conditional jump to a label
                Insn::Jmp(target) => {
                    match *target {
                        Target::CodePtr(code_ptr) => jmp_ptr(cb, code_ptr),
                        Target::Label(label) => jmp_label(cb, label),
                        Target::Block(ref edge) => jmp_label(cb, self.block_label(edge.target)),
                        Target::SideExit(..) => unreachable!("Target::SideExit should have been compiled by compile_exits"),
                    }
                }

                Insn::Je(target) => {
                    match *target {
                        Target::CodePtr(code_ptr) => je_ptr(cb, code_ptr),
                        Target::Label(label) => je_label(cb, label),
                        Target::Block(ref edge) => je_label(cb, self.block_label(edge.target)),
                        Target::SideExit(..) => unreachable!("Target::SideExit should have been compiled by compile_exits"),
                    }
                }

                Insn::Jne(target) => {
                    match *target {
                        Target::CodePtr(code_ptr) => jne_ptr(cb, code_ptr),
                        Target::Label(label) => jne_label(cb, label),
                        Target::Block(ref edge) => jne_label(cb, self.block_label(edge.target)),
                        Target::SideExit(..) => unreachable!("Target::SideExit should have been compiled by compile_exits"),
                    }
                }

                Insn::Jl(target) => {
                    match *target {
                        Target::CodePtr(code_ptr) => jl_ptr(cb, code_ptr),
                        Target::Label(label) => jl_label(cb, label),
                        Target::Block(ref edge) => jl_label(cb, self.block_label(edge.target)),
                        Target::SideExit(..) => unreachable!("Target::SideExit should have been compiled by compile_exits"),
                    }
                },

                Insn::Jg(target) => {
                    match *target {
                        Target::CodePtr(code_ptr) => jg_ptr(cb, code_ptr),
                        Target::Label(label) => jg_label(cb, label),
                        Target::Block(ref edge) => jg_label(cb, self.block_label(edge.target)),
                        Target::SideExit(..) => unreachable!("Target::SideExit should have been compiled by compile_exits"),
                    }
                },

                Insn::Jge(target) => {
                    match *target {
                        Target::CodePtr(code_ptr) => jge_ptr(cb, code_ptr),
                        Target::Label(label) => jge_label(cb, label),
                        Target::Block(ref edge) => jge_label(cb, self.block_label(edge.target)),
                        Target::SideExit(..) => unreachable!("Target::SideExit should have been compiled by compile_exits"),
                    }
                },

                Insn::Jbe(target) => {
                    match *target {
                        Target::CodePtr(code_ptr) => jbe_ptr(cb, code_ptr),
                        Target::Label(label) => jbe_label(cb, label),
                        Target::Block(ref edge) => jbe_label(cb, self.block_label(edge.target)),
                        Target::SideExit(..) => unreachable!("Target::SideExit should have been compiled by compile_exits"),
                    }
                },

                Insn::Jb(target) => {
                    match *target {
                        Target::CodePtr(code_ptr) => jb_ptr(cb, code_ptr),
                        Target::Label(label) => jb_label(cb, label),
                        Target::Block(ref edge) => jb_label(cb, self.block_label(edge.target)),
                        Target::SideExit(..) => unreachable!("Target::SideExit should have been compiled by compile_exits"),
                    }
                },

                Insn::Jz(target) => {
                    match *target {
                        Target::CodePtr(code_ptr) => jz_ptr(cb, code_ptr),
                        Target::Label(label) => jz_label(cb, label),
                        Target::Block(ref edge) => jz_label(cb, self.block_label(edge.target)),
                        Target::SideExit(..) => unreachable!("Target::SideExit should have been compiled by compile_exits"),
                    }
                }

                Insn::Jnz(target) => {
                    match *target {
                        Target::CodePtr(code_ptr) => jnz_ptr(cb, code_ptr),
                        Target::Label(label) => jnz_label(cb, label),
                        Target::Block(ref edge) => jnz_label(cb, self.block_label(edge.target)),
                        Target::SideExit(..) => unreachable!("Target::SideExit should have been compiled by compile_exits"),
                    }
                }

                Insn::Jo(target) |
                Insn::JoMul(target) => {
                    match *target {
                        Target::CodePtr(code_ptr) => jo_ptr(cb, code_ptr),
                        Target::Label(label) => jo_label(cb, label),
                        Target::Block(ref edge) => jo_label(cb, self.block_label(edge.target)),
                        Target::SideExit(..) => unreachable!("Target::SideExit should have been compiled by compile_exits"),
                    }
                }

                Insn::Joz(..) | Insn::Jonz(..) => unreachable!("Joz/Jonz should be unused for now"),

                Insn::PatchPoint(..) => unreachable!("PatchPoint should have been lowered to PatchPointPad in x86_scratch_split"),
                Insn::PatchPointPad => {
                    emit_pad_after_patch_point(cb, last_patch_pos);
                    // This position is itself where a jump gets written on invalidation, so it
                    // becomes what following code has to keep its distance from.
                    last_patch_pos = Some(cb.get_write_pos());
                },
                Insn::BoundaryPad => {
                    // A boundary is never patched, so it doesn't become a position to keep away
                    // from. The last patch point stays that, and the pad just gave it its room.
                    emit_pad_after_patch_point(cb, last_patch_pos);
                },

                // Atomically increment a counter at a given memory location
                Insn::IncrCounter { mem, value } => {
                    assert!(matches!(value, Opnd::UImm(_) | Opnd::Imm(_) ) );
                    write_lock_prefix(cb);
                    add(cb, mem.into(), value.into());
                },

                Insn::Breakpoint => int3(cb),
                Insn::Abort => ud2(cb),

                Insn::CSelZ { truthy, falsy, out } => {
                    emit_csel(cb, *truthy, *falsy, *out, cmovnz);
                },
                Insn::CSelNZ { truthy, falsy, out } => {
                    emit_csel(cb, *truthy, *falsy, *out, cmovz);
                },
                Insn::CSelE { truthy, falsy, out } => {
                    emit_csel(cb, *truthy, *falsy, *out, cmovne);
                },
                Insn::CSelNE { truthy, falsy, out } => {
                    emit_csel(cb, *truthy, *falsy, *out, cmove);
                },
                Insn::CSelL { truthy, falsy, out } => {
                    emit_csel(cb, *truthy, *falsy, *out, cmovge);
                },
                Insn::CSelLE { truthy, falsy, out } => {
                    emit_csel(cb, *truthy, *falsy, *out, cmovg);
                },
                Insn::CSelG { truthy, falsy, out } => {
                    emit_csel(cb, *truthy, *falsy, *out, cmovle);
                },
                Insn::CSelGE { truthy, falsy, out } => {
                    emit_csel(cb, *truthy, *falsy, *out, cmovl);
                }
            };

            insn_idx += 1;
        }

        // Error if we couldn't write out everything
        if cb.has_dropped_bytes() {
            Err(CompileError::OutOfMemory)
        } else {
            // No bytes dropped, so the pos markers point to valid code
            for (insn_idx, pos) in pos_markers {
                if let Insn::PosMarker(callback) = insns.get(insn_idx).unwrap() {
                    callback(pos, cb);
                } else {
                    panic!("non-PosMarker in pos_markers insn_idx={insn_idx} {self:?}");
                }
            }

            Ok(gc_offsets)
        }
    }

    /// Optimize and compile the stored instructions
    pub fn compile_with_regs(self, cb: &mut CodeBlock, regs: Vec<Reg>) -> Result<(CodePtr, Vec<CodePtr>), CompileError> {
        // The backend is allowed to use scratch registers only if it has not accepted them so far.
        let use_scratch_regs = !self.accept_scratch_reg;
        let mut regs = RegPool::new(regs);
        asm_dump!(self, init);

        let mut asm = trace_compile_phase("split", || self.x86_split());

        asm_dump!(asm, split);

        trace_compile_phase("regalloc", || {
            trace_compile_phase("number_instructions", || asm.number_instructions(0));

            let live_in = trace_compile_phase("analyze_liveness", || asm.analyze_liveness());
            let mut intervals = trace_compile_phase("build_intervals", || asm.build_intervals(live_in));

            // Dump live intervals if requested
            if let Some(crate::options::Options { dump_lir: Some(dump_lirs), .. }) = unsafe { crate::options::OPTIONS.as_ref() } {
                if dump_lirs.contains(&crate::options::DumpLIR::live_intervals) {
                    println!("LIR live_intervals:\n{}", crate::backend::lir::debug_intervals(&asm, &intervals));
                }
            }

            trace_compile_phase("preferred_registers", || asm.preferred_register_assignments(&mut intervals, &mut regs));
            let num_stack_slots = trace_compile_phase("linear_scan", || asm.linear_scan(&intervals, &regs));

            asm.stack_state.num_spill_slots = num_stack_slots;
            asm.record_spill_slots(&intervals);
            asm.stack_state.num_side_exit_stack_map_slots = asm.side_exit_stack_map_slots(&intervals);
            let stack_slot_count = asm.stack_state.stack_slot_count();
            if stack_slot_count > Self::MAX_FRAME_STACK_SLOTS {
                return Err(CompileError::NativeStackTooLarge);
            }

            // Dump vreg-to-physical-register mapping if requested
            if let Some(crate::options::Options { dump_lir: Some(dump_lirs), .. }) = unsafe { crate::options::OPTIONS.as_ref() } {
                if dump_lirs.contains(&crate::options::DumpLIR::alloc_regs) {
                    println!("LIR live_intervals:\n{}", crate::backend::lir::debug_intervals(&asm, &intervals));

                    println!("VReg assignments:");
                    for (i, interval) in intervals.iter().enumerate() {
                        if let Some(alloc) = interval.assigned.get() {
                            let alloc_str = match alloc {
                                Allocation::Reg(n) => format!("{}", regs.reg_at(n)),
                                Allocation::Stack(n) => format!("Stack[{}]", n),
                            };
                            println!("  v{} => {} (ranges: {})", i, alloc_str, interval.ranges_string());
                        }
                    }
                }
            }

            // Update FrameSetup slot_count now that StackState knows the
            // register allocator spill and side-exit capture counts.
            trace_compile_phase("count_stack_slots", || {
                for block in asm.basic_blocks.iter_mut() {
                    for insn in block.insns.iter_mut() {
                        if let Insn::FrameSetup { slot_count, .. } = insn {
                            *slot_count = stack_slot_count;
                        }
                    }
                }
            });

            trace_compile_phase("resolve_ssa", || {
                asm.handle_caller_saved_regs(&intervals, &regs, &C_ARG_REGREGS);
                asm.resolve_ssa(&intervals, &regs);
            });

            Ok(())
        })?;
        asm_dump!(asm, alloc_regs);

        // We are moved out of SSA after resolve_ssa

        // We put compile_exits after alloc_regs to avoid extending live ranges for VRegs spilled on side exits.
        // Exit code is compiled into a separate list of instructions that we append
        // to the last reachable block before scratch_split, so it gets linearized and split.
        trace_compile_phase("compile_exits", || {
            let exit_insns = asm.compile_exits();

            // Append exit instructions to the last reachable block so they are
            // included in linearize_instructions and processed by scratch_split.
            if let Some(&last_block) = asm.block_order().last() {
                for insn in exit_insns {
                    asm.basic_blocks[last_block.0].insns.push(insn);
                    asm.basic_blocks[last_block.0].insn_ids.push(None);
                }
            }
        });
        asm_dump!(asm, compile_exits);

        if use_scratch_regs {
            asm = trace_compile_phase("scratch_split", || asm.x86_scratch_split());
            asm_dump!(asm, scratch_split);
        } else {
            // For trampolines that use scratch registers, resolve ParallelMov without scratch_reg.
            asm = trace_compile_phase("resolve_parallel_mov", || asm.resolve_parallel_mov_pass());
            asm_dump!(asm, resolve_parallel_mov);
        }

        trace_compile_phase("emit", || {
            // Create label instances in the code block
            for (idx, name) in asm.label_names.iter().enumerate() {
                let label = cb.new_label(name.to_string());
                assert_eq!(label, Label(idx));
            }

            let start_ptr = cb.get_write_ptr();
            let gc_offsets = asm.x86_emit(cb).inspect_err(|_| cb.clear_labels())?;
            assert!(!cb.has_dropped_bytes(), "emit should not drop bytes without error");

            cb.link_labels().or(Err(CompileError::LabelLinkingFailure))?;
            Ok((start_ptr, gc_offsets))
        })
    }
}

#[cfg(test)]
mod tests {
    use insta::assert_snapshot;
    use crate::assert_disasm_snapshot;
    use crate::options::rb_zjit_prepare_options;
    use super::*;

    const BOLD_BEGIN: &str = "\x1b[1m";
    const BOLD_END: &str = "\x1b[22m";

    fn setup_asm() -> (Assembler, CodeBlock) {
        rb_zjit_prepare_options(); // for get_option! on asm.compile
        let mut asm = Assembler::new();
        asm.new_block_without_id("test");
        (asm, CodeBlock::new_dummy())
    }

    /// Number of spill slots [`split_binop`] pre-registers, so tests can use
    /// [`spilled`] without running register allocation.
    const NUM_TEST_SPILL_SLOTS: usize = 4;

    /// A VReg the register allocator spilled to frame slot `stack_idx`. After register
    /// allocation, a surviving VReg *means* spilled.
    fn spilled(stack_idx: StackIdx) -> Opnd {
        Opnd::VReg { idx: VRegId(stack_idx as VRegIdBase), num_bits: 64 }
    }

    #[derive(Clone, Copy, Debug)]
    enum BinOpKind {
        Add,
        Sub,
        And,
        Or,
        Xor,
    }

    fn split_binop(kind: BinOpKind, left: Opnd, right: Opnd, out: Opnd) -> Assembler {
        let (mut asm, _) = setup_asm();
        asm.num_vregs = NUM_TEST_SPILL_SLOTS;
        asm.stack_state.num_spill_slots = NUM_TEST_SPILL_SLOTS;
        asm.spill_slots = (0..NUM_TEST_SPILL_SLOTS).map(|i| Some(i as StackIdx)).collect();
        match kind {
            BinOpKind::Add => asm.push_insn(Insn::Add { left, right, out }),
            BinOpKind::Sub => asm.push_insn(Insn::Sub { left, right, out }),
            BinOpKind::And => asm.push_insn(Insn::And { left, right, out }),
            BinOpKind::Or => asm.push_insn(Insn::Or { left, right, out }),
            BinOpKind::Xor => asm.push_insn(Insn::Xor { left, right, out }),
        }
        asm.x86_scratch_split()
    }

    fn binop_mnemonic(kind: BinOpKind) -> &'static str {
        match kind {
            BinOpKind::Add => "add",
            BinOpKind::Sub => "sub",
            BinOpKind::And => "and",
            BinOpKind::Or => "or",
            BinOpKind::Xor => "xor",
        }
    }

    fn split_binop_disasm_lines(kind: BinOpKind, left: Opnd, right: Opnd, out: Opnd) -> Vec<String> {
        let mut asm = split_binop(kind, left, right, out);
        let mut cb = CodeBlock::new_dummy();
        for name in &asm.label_names {
            cb.new_label(name.to_string());
        }
        assert!(asm.x86_emit(&mut cb).is_ok(), "{kind:?}: x86_emit failed");

        cb.disasm()
            .lines()
            .map(str::trim)
            .filter(|line| !line.is_empty())
            .map(|line| {
                line.split_once(": ")
                    .map(|(_, rest)| rest.to_string())
                    .unwrap_or_else(|| line.to_string())
            })
            .collect()
    }

    fn assert_split_binop_case(kind: BinOpKind, left: Opnd, right: Opnd, out: Opnd, case: &str) {
        fn reg_names(reg: Reg) -> (&'static str, &'static str) {
            const RAX_NO: u8 = RAX_REG.reg_no;
            const RDI_NO: u8 = RDI_REG.reg_no;
            const R13_NO: u8 = R13_REG.reg_no;
            match reg.reg_no {
                RAX_NO => ("rax", "eax"),
                RDI_NO => ("rdi", "edi"),
                R13_NO => ("r13", "r13d"),
                _ => panic!("unexpected register in test helper: {reg:?}"),
            }
        }

        let lines = split_binop_disasm_lines(kind, left, right, out);
        let mnemonic = binop_mnemonic(kind);
        let matching: Vec<(usize, &String)> = lines.iter()
            .enumerate()
            .filter(|(_, line)| line.starts_with(&format!("{mnemonic} ")))
            .collect();

        assert_eq!(matching.len(), 1, "{kind:?} {case}: expected exactly one `{mnemonic}` in disasm, got {lines:?}");
        assert!(
            !matching[0].1.contains("], qword ptr ["),
            "{kind:?} {case}: emitted mem/mem `{mnemonic}` in disasm {lines:?}"
        );

        if let (Opnd::Reg(out_reg), Opnd::Imm(_) | Opnd::UImm(_)) = (out, left) {
            let (out64, out32) = reg_names(out_reg);
            let prelude = &lines[..matching[0].0];
            assert!(
                prelude.iter().any(|line|
                    line.starts_with(&format!("mov {out64}, ")) ||
                    line.starts_with(&format!("mov {out32}, ")) ||
                    line.starts_with(&format!("movabs {out64}, "))
                ),
                "{kind:?} {case}: expected left immediate to be materialized into output register before `{mnemonic}`, got {lines:?}"
            );
        }

        if matches!(right, Opnd::Imm(value) if imm_num_bits(value) > 32)
            || matches!(right, Opnd::UImm(value) if imm_num_bits(value as i64) > 32)
        {
            assert!(lines.iter().any(|line| line.starts_with("movabs ")), "{kind:?} {case}: expected movabs materialization for 64-bit immediate, got {lines:?}");
        }
    }

    #[test]
    fn test_fallthrough_to_a_patchpoint() {
        // At one point, this generated unnecessary nop padding
        use crate::cruby::test_utils::{compile_to_iseq, with_rubyvm};
        use crate::hir::Invariant;
        use crate::payload::IseqVersion;

        let version = IseqVersion::new(compile_to_iseq("nil"));

        // The PosMarker that split_patch_point() installs registers the patch point
        // with ZJITState's invariant table while emitting, so the VM has to be booted.
        let cb = with_rubyvm(|| {
            crate::options::rb_zjit_prepare_options(); // Allow `get_option!` in Assembler
            let mut asm = Assembler::new();
            let mut cb = CodeBlock::new_dummy();

            let bb0 = asm.new_block(crate::hir::BlockId(0), true, 0);
            let bb1 = asm.new_block(crate::hir::BlockId(1), false, 1);

            // The patch point's target only has to resolve to some address for the
            // PosMarker that records it, so bb0 stands in for the side exit code.
            let side_exit = asm.new_label("side_exit");

            // bb0 falls through to bb1
            asm.set_current_block(bb0);
            let label_bb0 = asm.new_label("bb0");
            asm.write_label(label_bb0);
            asm.write_label(side_exit.clone());
            asm.mov(C_ARG_OPNDS[0], Opnd::UImm(1));
            asm.push_insn(Insn::Jmp(Target::Block(Box::new(BranchEdge { target: bb1, args: vec![] }))));

            asm.set_current_block(bb1);
            let label_bb1 = asm.new_label("bb1");
            asm.write_label(label_bb1);
            asm.patch_point(side_exit.clone(), Invariant::SingleRactorMode, version);
            asm.cret(C_ARG_OPNDS[0]);

            asm.compile_with_num_regs(&mut cb, 0);
            cb
        });

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov edi, 1
        0x5: mov rax, rdi
        0x8: ret
        0x9: nop
        ");
        assert_snapshot!(cb.hexdump(), @"bf010000004889f8c390");
    }

    #[test]
    fn test_lir_string() {
        use crate::hir::SideExitReason;

        let mut asm = Assembler::new();
        asm.new_block_without_id("test");
        asm.stack_state.stack_base_idx = 1;

        let label = asm.new_label("bb0");
        asm.write_label(label.clone());
        asm.push_insn(Insn::Comment("bb0(): foo@/tmp/a.rb:1".into()));
        asm.frame_setup(JIT_PRESERVED_REGS);

        let val64 = asm.add(CFP, Opnd::UImm(64));
        asm.store(Mem::new(64, SP, 0x10), val64);
        let side_exit = Target::SideExit(Box::new(SideExitTarget { reason: SideExitReason::Interrupt, exit: SideExit { pc: 0.into(), iseq: std::ptr::null(), stack: vec![], locals: vec![], stack_map: None, recompile: None } }));
        asm.push_insn(Insn::Joz(val64, side_exit));
        asm.mov(C_ARG_OPNDS[0], C_RET_OPND.with_num_bits(32));
        asm.load_mem_into(C_ARG_OPNDS[1], Mem::new(64, SP, -8));

        let val32 = asm.sub(Opnd::Value(Qtrue), Opnd::Imm(1));
        asm.store(Mem::new(32, EC, 0x10), val32.with_num_bits(32));
        asm.push_insn(Insn::Je(label));
        asm.cret(val64);

        asm.frame_teardown(JIT_PRESERVED_REGS);
        assert_disasm_snapshot!(lir_string(&mut asm), @"
        test():
        bb0():
          # bb0(): foo@/tmp/a.rb:1
          FrameSetup 1, r13, rbx, r12
          v0 = Add r13, 0x40
          Store [rbx + 0x10], v0
          Joz Exit(Interrupt), v0
          Mov rdi, eax
          LoadMemInto rsi, [rbx - 8]
          v1 = Sub Value(0x14), Imm(1)
          Store Mem32[r12 + 0x10], VReg32(v1)
          Je bb0
          CRet v0
          FrameTeardown r13, rbx, r12
        ");
    }

    #[test]
    #[ignore]
    fn test_emit_add_lt_32_bits() {
        let (mut asm, mut cb) = setup_asm();

        let _ = asm.add(Opnd::Reg(RAX_REG), Opnd::UImm(0xFF));
        asm.compile_with_num_regs(&mut cb, 1);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov rax, rax
        0x3: add rax, 0xff
        ");
        assert_snapshot!(cb.hexdump(), @"4889c04881c0ff000000");
    }

    #[test]
    #[ignore]
    fn test_emit_add_gt_32_bits() {
        let (mut asm, mut cb) = setup_asm();

        let _ = asm.add(Opnd::Reg(RAX_REG), Opnd::UImm(0xFFFF_FFFF_FFFF));
        asm.compile_with_num_regs(&mut cb, 1);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov rax, rax
        0x3: movabs r11, 0xffffffffffff
        0xd: add rax, r11
        ");
        assert_snapshot!(cb.hexdump(), @"4889c049bbffffffffffff00004c01d8");
    }

    #[test]
    #[ignore]
    fn test_emit_and_lt_32_bits() {
        let (mut asm, mut cb) = setup_asm();

        let _ = asm.and(Opnd::Reg(RAX_REG), Opnd::UImm(0xFF));
        asm.compile_with_num_regs(&mut cb, 1);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov rax, rax
        0x3: and rax, 0xff
        ");
        assert_snapshot!(cb.hexdump(), @"4889c04881e0ff000000");
    }

    #[test]
    #[ignore]
    fn test_emit_and_gt_32_bits() {
        let (mut asm, mut cb) = setup_asm();

        let _ = asm.and(Opnd::Reg(RAX_REG), Opnd::UImm(0xFFFF_FFFF_FFFF));
        asm.compile_with_num_regs(&mut cb, 1);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov rax, rax
        0x3: movabs r11, 0xffffffffffff
        0xd: and rax, r11
        ");
        assert_snapshot!(cb.hexdump(), @"4889c049bbffffffffffff00004c21d8");
    }

    #[test]
    fn test_emit_cmp_lt_32_bits() {
        let (mut asm, mut cb) = setup_asm();

        asm.cmp(Opnd::Reg(RAX_REG), Opnd::UImm(0xFF));
        asm.compile_with_num_regs(&mut cb, 0);

        assert_disasm_snapshot!(cb.disasm(), @"  0x0: cmp rax, 0xff");
        assert_snapshot!(cb.hexdump(), @"4881f8ff000000");
    }

    #[test]
    fn test_emit_cmp_gt_32_bits() {
        let (mut asm, mut cb) = setup_asm();

        asm.cmp(Opnd::Reg(RAX_REG), Opnd::UImm(0xFFFF_FFFF_FFFF));
        asm.compile_with_num_regs(&mut cb, 0);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: movabs r10, 0xffffffffffff
        0xa: cmp rax, r10
        ");
        assert_snapshot!(cb.hexdump(), @"49baffffffffffff00004c39d0");
    }

    #[test]
    fn test_emit_cmp_64_bits() {
        let (mut asm, mut cb) = setup_asm();

        asm.cmp(Opnd::Reg(RAX_REG), Opnd::UImm(0xFFFF_FFFF_FFFF_FFFF));
        asm.compile_with_num_regs(&mut cb, 0);

        assert_disasm_snapshot!(cb.disasm(), @"  0x0: cmp rax, -1");
        assert_snapshot!(cb.hexdump(), @"4883f8ff");
    }

    #[test]
    fn test_emit_cmp_mem_16_bits_with_imm_16() {
        let (mut asm, mut cb) = setup_asm();

        let shape_opnd = asm.load_mem(Mem::new(16, Opnd::Reg(RAX_REG), 6));

        asm.cmp(shape_opnd, Opnd::UImm(0xF000));
        asm.compile_with_num_regs(&mut cb, 0);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov r10w, word ptr [rax + 6]
        0x5: mov word ptr [rbp - 8], r10w
        0xa: mov r11w, word ptr [rbp - 8]
        0xf: cmp r11w, 0xf000
        ");
        assert_snapshot!(cb.hexdump(), @"66448b500666448955f866448b5df8664181fb00f0");
    }

    #[test]
    fn test_emit_cmp_mem_32_bits_with_imm_32() {
        let (mut asm, mut cb) = setup_asm();

        let shape_opnd = asm.load_mem(Mem::new(32, Opnd::Reg(RAX_REG), 4));

        asm.cmp(shape_opnd, Opnd::UImm(0xF000_0000));
        asm.compile_with_num_regs(&mut cb, 0);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov r10d, dword ptr [rax + 4]
        0x4: mov dword ptr [rbp - 8], r10d
        0x8: mov r11d, dword ptr [rbp - 8]
        0xc: cmp r11d, 0xf0000000
        ");
        assert_snapshot!(cb.hexdump(), @"448b5004448955f8448b5df84181fb000000f0");
    }

    #[test]
    #[ignore]
    fn test_emit_or_lt_32_bits() {
        let (mut asm, mut cb) = setup_asm();

        let _ = asm.or(Opnd::Reg(RAX_REG), Opnd::UImm(0xFF));
        asm.compile_with_num_regs(&mut cb, 1);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov rax, rax
        0x3: or rax, 0xff
        ");
        assert_snapshot!(cb.hexdump(), @"4889c04881c8ff000000");
    }

    #[test]
    #[ignore]
    fn test_emit_or_gt_32_bits() {
        let (mut asm, mut cb) = setup_asm();

        let _ = asm.or(Opnd::Reg(RAX_REG), Opnd::UImm(0xFFFF_FFFF_FFFF));
        asm.compile_with_num_regs(&mut cb, 1);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov rax, rax
        0x3: movabs r11, 0xffffffffffff
        0xd: or rax, r11
        ");
        assert_snapshot!(cb.hexdump(), @"4889c049bbffffffffffff00004c09d8");
    }

    #[test]
    #[ignore]
    fn test_emit_sub_lt_32_bits() {
        let (mut asm, mut cb) = setup_asm();

        let _ = asm.sub(Opnd::Reg(RAX_REG), Opnd::UImm(0xFF));
        asm.compile_with_num_regs(&mut cb, 1);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov rax, rax
        0x3: sub rax, 0xff
        ");
        assert_snapshot!(cb.hexdump(), @"4889c04881e8ff000000");
    }

    #[test]
    #[ignore]
    fn test_emit_sub_gt_32_bits() {
        let (mut asm, mut cb) = setup_asm();

        let _ = asm.sub(Opnd::Reg(RAX_REG), Opnd::UImm(0xFFFF_FFFF_FFFF));
        asm.compile_with_num_regs(&mut cb, 1);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov rax, rax
        0x3: movabs r11, 0xffffffffffff
        0xd: sub rax, r11
        ");
        assert_snapshot!(cb.hexdump(), @"4889c049bbffffffffffff00004c29d8");
    }

    #[test]
    fn test_emit_test_lt_32_bits() {
        let (mut asm, mut cb) = setup_asm();

        asm.test(Opnd::Reg(RAX_REG), Opnd::UImm(0xFF));
        asm.compile_with_num_regs(&mut cb, 0);

        assert_disasm_snapshot!(cb.disasm(), @"  0x0: test rax, 0xff");
        assert_snapshot!(cb.hexdump(), @"48f7c0ff000000");
    }

    #[test]
    fn test_emit_test_gt_32_bits() {
        let (mut asm, mut cb) = setup_asm();

        asm.test(Opnd::Reg(RAX_REG), Opnd::UImm(0xFFFF_FFFF_FFFF));
        asm.compile_with_num_regs(&mut cb, 0);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: movabs r10, 0xffffffffffff
        0xa: test rax, r10
        ");
        assert_snapshot!(cb.hexdump(), @"49baffffffffffff00004c85d0");
    }

    #[test]
    #[ignore]
    fn test_emit_xor_lt_32_bits() {
        let (mut asm, mut cb) = setup_asm();

        let _ = asm.xor(Opnd::Reg(RAX_REG), Opnd::UImm(0xFF));
        asm.compile_with_num_regs(&mut cb, 1);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov rax, rax
        0x3: xor rax, 0xff
        ");
        assert_snapshot!(cb.hexdump(), @"4889c04881f0ff000000");
    }

    #[test]
    #[ignore]
    fn test_emit_xor_gt_32_bits() {
        let (mut asm, mut cb) = setup_asm();

        let _ = asm.xor(Opnd::Reg(RAX_REG), Opnd::UImm(0xFFFF_FFFF_FFFF));
        asm.compile_with_num_regs(&mut cb, 1);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov rax, rax
        0x3: movabs r11, 0xffffffffffff
        0xd: xor rax, r11
        ");
        assert_snapshot!(cb.hexdump(), @"4889c049bbffffffffffff00004c31d8");
    }

    #[test]
    fn test_merge_lea_reg() {
        let (mut asm, mut cb) = setup_asm();

        let sp = asm.lea(Mem::new(64, SP, 8));
        asm.mov(SP, sp); // should be merged to lea
        asm.compile_with_num_regs(&mut cb, 1);

        assert_disasm_snapshot!(cb.disasm(), @"  0x0: lea rbx, [rbx + 8]");
        assert_snapshot!(cb.hexdump(), @"488d5b08");
    }

    #[test]
    #[ignore]
    fn test_merge_lea_mem() {
        let (mut asm, mut cb) = setup_asm();

        let sp = asm.lea(Mem::new(64, SP, 8));
        asm.store(Mem::new(64, SP, 0), sp); // should NOT be merged to lea
        asm.compile_with_num_regs(&mut cb, 1);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: movabs r11, 0xffffffffffff
        0xa: cmp rax, r11
        ");
        assert_snapshot!(cb.hexdump(), @"49bbffffffffffff00004c39d8");
    }

    #[test]
    #[ignore]
    fn test_replace_cmp_0() {
        let (mut asm, mut cb) = setup_asm();

        let val = asm.load_mem(Mem::new(64, SP, 8));
        asm.cmp(val, 0.into());
        let result = asm.csel_e(Qtrue.into(), Qfalse.into());
        asm.mov(Opnd::Reg(RAX_REG), result);
        asm.compile_with_num_regs(&mut cb, 2);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov rax, qword ptr [rbx + 8]
        0x4: test rax, rax
        0x7: mov eax, 0x14
        0xc: mov ecx, 0
        0x11: cmovne rax, rcx
        0x15: mov rax, rax
        ");
        assert_snapshot!(cb.hexdump(), @"488b43084885c0b814000000b900000000480f45c14889c0");
    }

    #[test]
    fn test_merge_add_mov() {
        let (mut asm, mut cb) = setup_asm();

        let sp = asm.add(CFP, Opnd::UImm(0x40));
        asm.mov(CFP, sp); // should be merged to add
        asm.compile_with_num_regs(&mut cb, 1);

        assert_disasm_snapshot!(cb.disasm(), @"  0x0: add r13, 0x40");
        assert_snapshot!(cb.hexdump(), @"4983c540");
    }

    #[test]
    fn test_add_into() {
        let (mut asm, mut cb) = setup_asm();

        asm.add_into(CFP, Opnd::UImm(0x40));
        asm.compile_with_num_regs(&mut cb, 1);

        assert_disasm_snapshot!(cb.disasm(), @"  0x0: add r13, 0x40");
        assert_snapshot!(cb.hexdump(), @"4983c540");
    }

    #[test]
    fn test_merge_sub_mov() {
        let (mut asm, mut cb) = setup_asm();

        let sp = asm.sub(CFP, Opnd::UImm(0x40));
        asm.mov(CFP, sp); // should be merged to add
        asm.compile_with_num_regs(&mut cb, 1);

        assert_disasm_snapshot!(cb.disasm(), @"  0x0: sub r13, 0x40");
        assert_snapshot!(cb.hexdump(), @"4983ed40");
    }

    #[test]
    fn test_sub_into() {
        let (mut asm, mut cb) = setup_asm();

        asm.sub_into(CFP, Opnd::UImm(0x40));
        asm.compile_with_num_regs(&mut cb, 1);

        assert_disasm_snapshot!(cb.disasm(), @"  0x0: sub r13, 0x40");
        assert_snapshot!(cb.hexdump(), @"4983ed40");
    }

    #[test]
    fn test_merge_and_mov() {
        let (mut asm, mut cb) = setup_asm();

        let sp = asm.and(CFP, Opnd::UImm(0x40));
        asm.mov(CFP, sp); // should be merged to add
        asm.compile_with_num_regs(&mut cb, 1);

        assert_disasm_snapshot!(cb.disasm(), @"  0x0: and r13, 0x40");
        assert_snapshot!(cb.hexdump(), @"4983e540");
    }

    #[test]
    fn test_merge_or_mov() {
        let (mut asm, mut cb) = setup_asm();

        let sp = asm.or(CFP, Opnd::UImm(0x40));
        asm.mov(CFP, sp); // should be merged to add
        asm.compile_with_num_regs(&mut cb, 1);

        assert_disasm_snapshot!(cb.disasm(), @"  0x0: or r13, 0x40");
        assert_snapshot!(cb.hexdump(), @"4983cd40");
    }

    #[test]
    fn test_merge_xor_mov() {
        let (mut asm, mut cb) = setup_asm();

        let sp = asm.xor(CFP, Opnd::UImm(0x40));
        asm.mov(CFP, sp); // should be merged to add
        asm.compile_with_num_regs(&mut cb, 1);

        assert_disasm_snapshot!(cb.disasm(), @"  0x0: xor r13, 0x40");
        assert_snapshot!(cb.hexdump(), @"4983f540");
    }

    #[test]
    fn test_ccall_resolve_parallel_moves_no_cycle() {
        crate::options::rb_zjit_prepare_options();
        let (mut asm, mut cb) = setup_asm();

        asm.ccall(0 as _, vec![
            C_ARG_OPNDS[0], // mov rdi, rdi (optimized away)
            C_ARG_OPNDS[1], // mov rsi, rsi (optimized away)
        ]);
        asm.compile_with_num_regs(&mut cb, ALLOC_REGS.len());

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov eax, 0
        0x5: call rax
        ");
        assert_snapshot!(cb.hexdump(), @"b800000000ffd0");
    }

    #[test]
    fn test_ccall_resolve_parallel_moves_single_cycle() {
        crate::options::rb_zjit_prepare_options();
        let (mut asm, mut cb) = setup_asm();

        // rdi and rsi form a cycle
        asm.ccall(0 as _, vec![
            C_ARG_OPNDS[1], // mov rdi, rsi
            C_ARG_OPNDS[0], // mov rsi, rdi
            C_ARG_OPNDS[2], // mov rdx, rdx (optimized away)
        ]);
        asm.compile_with_num_regs(&mut cb, ALLOC_REGS.len());

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov r11, rsi
        0x3: mov rsi, rdi
        0x6: mov rdi, r11
        0x9: mov eax, 0
        0xe: call rax
        ");
        assert_snapshot!(cb.hexdump(), @"4989f34889fe4c89dfb800000000ffd0");
    }

    #[test]
    fn test_ccall_resolve_parallel_moves_two_cycles() {
        crate::options::rb_zjit_prepare_options();
        let (mut asm, mut cb) = setup_asm();

        // rdi and rsi form a cycle, and rdx and rcx form another cycle
        asm.ccall(0 as _, vec![
            C_ARG_OPNDS[1], // mov rdi, rsi
            C_ARG_OPNDS[0], // mov rsi, rdi
            C_ARG_OPNDS[3], // mov rdx, rcx
            C_ARG_OPNDS[2], // mov rcx, rdx
        ]);
        asm.compile_with_num_regs(&mut cb, ALLOC_REGS.len());

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov r11, rcx
        0x3: mov rcx, rdx
        0x6: mov rdx, r11
        0x9: mov r11, rsi
        0xc: mov rsi, rdi
        0xf: mov rdi, r11
        0x12: mov eax, 0
        0x17: call rax
        ");
        assert_snapshot!(cb.hexdump(), @"4989cb4889d14c89da4989f34889fe4c89dfb800000000ffd0");
    }

    #[test]
    fn test_ccall_resolve_parallel_moves_large_cycle() {
        crate::options::rb_zjit_prepare_options();
        let (mut asm, mut cb) = setup_asm();

        // rdi, rsi, and rdx form a cycle
        asm.ccall(0 as _, vec![
            C_ARG_OPNDS[1], // mov rdi, rsi
            C_ARG_OPNDS[2], // mov rsi, rdx
            C_ARG_OPNDS[0], // mov rdx, rdi
        ]);
        asm.compile_with_num_regs(&mut cb, ALLOC_REGS.len());

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov r11, rdx
        0x3: mov rdx, rdi
        0x6: mov rdi, rsi
        0x9: mov rsi, r11
        0xc: mov eax, 0
        0x11: call rax
        ");
        assert_snapshot!(cb.hexdump(), @"4989d34889fa4889f74c89deb800000000ffd0");
    }

    #[test]
    #[ignore]
    fn test_ccall_resolve_parallel_moves_with_insn_out() {
        let (mut asm, mut cb) = setup_asm();

        let rax = asm.load(Opnd::UImm(1));
        let rcx = asm.load(Opnd::UImm(2));
        let rdx = asm.load(Opnd::UImm(3));
        // rcx and rdx form a cycle
        asm.ccall(0 as _, vec![
            rax, // mov rdi, rax
            rcx, // mov rsi, rcx
            rcx, // mov rdx, rcx
            rdx, // mov rcx, rdx
        ]);
        asm.compile_with_num_regs(&mut cb, 3);

        assert_disasm_snapshot!(cb.disasm(), @"
            0x0: mov eax, 1
            0x5: mov ecx, 2
            0xa: mov edx, 3
            0xf: mov rdi, rax
            0x12: mov rsi, rcx
            0x15: mov r11, rcx
            0x18: mov rcx, rdx
            0x1b: mov rdx, r11
            0x1e: mov eax, 0
            0x23: call rax
        ");
        assert_snapshot!(cb.hexdump(), @"b801000000b902000000ba030000004889c74889ce4989cb4889d14c89dab800000000ffd0");
    }

    #[test]
    fn test_ccall_register_preservation_even() {
        let (mut asm, mut cb) = setup_asm();

        let v0 = asm.load(1.into());
        let v1 = asm.load(2.into());
        let v2 = asm.load(3.into());
        let v3 = asm.load(4.into());
        asm.ccall(0 as _, vec![]);
        _ = asm.add(v0, v1);
        _ = asm.add(v2, v3);

        asm.compile_with_num_regs(&mut cb, ALLOC_REGS.len());

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov edi, 1
        0x5: mov esi, 2
        0xa: mov edx, 3
        0xf: mov ecx, 4
        0x14: push rdi
        0x15: push rsi
        0x16: push rdx
        0x17: push rcx
        0x18: mov eax, 0
        0x1d: call rax
        0x1f: pop rcx
        0x20: pop rdx
        0x21: pop rsi
        0x22: pop rdi
        0x23: add rdi, rsi
        0x26: mov rdi, rdx
        0x29: add rdi, rcx
        ");
        assert_snapshot!(cb.hexdump(), @"bf01000000be02000000ba03000000b90400000057565251b800000000ffd0595a5e5f4801f74889d74801cf");
    }

    #[test]
    fn test_ccall_register_preservation_odd() {
        let (mut asm, mut cb) = setup_asm();

        let v0 = asm.load(1.into());
        let v1 = asm.load(2.into());
        let v2 = asm.load(3.into());
        let v3 = asm.load(4.into());
        let v4 = asm.load(5.into());
        asm.ccall(0 as _, vec![]);
        _ = asm.add(v0, v1);
        _ = asm.add(v2, v3);
        _ = asm.add(v2, v4);

        asm.compile_with_num_regs(&mut cb, ALLOC_REGS.len());

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov edi, 1
        0x5: mov esi, 2
        0xa: mov edx, 3
        0xf: mov ecx, 4
        0x14: mov r8d, 5
        0x1a: push rdi
        0x1b: push rsi
        0x1c: push rdx
        0x1d: push rcx
        0x1e: push r8
        0x20: push 0
        0x22: mov eax, 0
        0x27: call rax
        0x29: pop r8
        0x2b: pop r8
        0x2d: pop rcx
        0x2e: pop rdx
        0x2f: pop rsi
        0x30: pop rdi
        0x31: add rdi, rsi
        0x34: mov rdi, rdx
        0x37: add rdi, rcx
        0x3a: mov rdi, rdx
        0x3d: add rdi, r8
        ");
        assert_snapshot!(cb.hexdump(), @"bf01000000be02000000ba03000000b90400000041b8050000005756525141506a00b800000000ffd041584158595a5e5f4801f74889d74801cf4889d74c01c7");
    }

    #[test]
    fn test_ccall_stack_args() {
        let (mut asm, mut cb) = setup_asm();

        // 7 arguments: 6 in registers, 1 on the stack. The outgoing-argument
        // area is padded to 16 bytes to keep the SP aligned at the call.
        let args: Vec<Opnd> = (1..=7).map(|i| asm.load(Opnd::UImm(i))).collect();
        asm.ccall(0 as _, args);

        asm.compile_with_num_regs(&mut cb, ALLOC_REGS.len());

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov edi, 1
        0x5: mov esi, 2
        0xa: mov edx, 3
        0xf: mov ecx, 4
        0x14: mov r8d, 5
        0x1a: mov r9d, 6
        0x20: mov eax, 7
        0x25: push 0
        0x27: push rax
        0x28: mov eax, 0
        0x2d: call rax
        0x2f: add rsp, 0x10
        ");
        assert_snapshot!(cb.hexdump(), @"bf01000000be02000000ba03000000b90400000041b80500000041b906000000b8070000006a0050b800000000ffd04883c410");
    }

    #[test]
    fn test_ccall_stack_args_spilled_source() {
        let (mut asm, mut cb) = setup_asm();

        // 8 arguments with more live values than allocatable registers, so a
        // stack argument's source is itself a frame-based spill slot.
        let args: Vec<Opnd> = (1..=8).map(|i| asm.load(Opnd::UImm(i))).collect();
        asm.ccall(0 as _, args);

        asm.compile_with_num_regs(&mut cb, ALLOC_REGS.len());

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov edi, 1
        0x5: mov esi, 2
        0xa: mov edx, 3
        0xf: mov ecx, 4
        0x14: mov r8d, 5
        0x1a: mov r9d, 6
        0x20: mov eax, 7
        0x25: mov r10d, 8
        0x2b: mov qword ptr [rbp - 8], r10
        0x2f: mov r11, qword ptr [rbp - 8]
        0x33: push r11
        0x35: push rax
        0x36: mov eax, 0
        0x3b: call rax
        0x3d: add rsp, 0x10
        ");
        assert_snapshot!(cb.hexdump(), @"bf01000000be02000000ba03000000b90400000041b80500000041b906000000b80700000041ba080000004c8955f84c8b5df8415350b800000000ffd04883c410");
    }

    #[test]
    fn test_ccall_stack_args_with_survivor() {
        let (mut asm, mut cb) = setup_asm();

        // 8 arguments (2 stack slots) with a value that survives the call.
        // The survivor's push/pop must bracket the outgoing-argument area's
        // sub/add: the bug that got GH-15312 reverted was stack-argument
        // stores overlapping the survivor slots, so the pops restored the
        // arguments instead of the saved registers.
        let surv = asm.load(Opnd::UImm(0x42));
        let a0 = asm.load(Opnd::UImm(1));
        let a1 = asm.load(Opnd::UImm(2));
        asm.ccall(0 as _, vec![a0, a1, a0, a1, a0, a1, a0, a1]);
        _ = asm.add(surv, Opnd::UImm(1));

        asm.compile_with_num_regs(&mut cb, ALLOC_REGS.len());

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov edi, 0x42
        0x5: mov esi, 1
        0xa: mov edx, 2
        0xf: push rdi
        0x10: push 0
        0x12: push rdx
        0x13: push rsi
        0x14: mov r9, rdx
        0x17: mov rdx, rsi
        0x1a: mov rsi, r9
        0x1d: mov r8, rdx
        0x20: mov rcx, r9
        0x23: mov rdi, rdx
        0x26: mov eax, 0
        0x2b: call rax
        0x2d: add rsp, 0x10
        0x31: pop rdi
        0x32: pop rdi
        0x33: add rdi, 1
        ");
        assert_snapshot!(cb.hexdump(), @"bf42000000be01000000ba02000000576a0052564989d14889f24c89ce4989d04c89c94889d7b800000000ffd04883c4105f5f4883c701");
    }

    #[test]
    fn test_cpush_pair() {
        let (mut asm, mut cb) = setup_asm();
        let v0 = asm.load(1.into());
        let v1 = asm.load(2.into());
        asm.cpush_pair(v0, v1);
        asm.compile_with_num_regs(&mut cb, ALLOC_REGS.len());

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov edi, 1
        0x5: mov esi, 2
        0xa: push rdi
        0xb: push rsi
        ");
        assert_snapshot!(cb.hexdump(), @"bf01000000be020000005756");
    }

    #[test]
    fn test_cpop_pair_into() {
        let (mut asm, mut cb) = setup_asm();
        let v0 = asm.load(1.into());
        let v1 = asm.load(2.into());
        asm.cpop_pair_into(v0, v1);
        asm.compile_with_num_regs(&mut cb, ALLOC_REGS.len());

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov edi, 1
        0x5: mov esi, 2
        0xa: pop rdi
        0xb: pop rsi
        ");
        assert_snapshot!(cb.hexdump(), @"bf01000000be020000005f5e");
    }

    #[test]
    fn test_cmov_mem() {
        let (mut asm, mut cb) = setup_asm();

        let top = Mem::new(64, SP, 0);
        let ary_opnd = SP;
        let array_len_opnd = asm.load_mem(Mem::new(64, SP, 16));

        asm.cmp(array_len_opnd, 1.into());
        let elem = asm.load_mem(Mem::new(64, ary_opnd, 0));
        let elem_opnd = asm.csel_g(elem, Qnil.into());
        asm.store(top, elem_opnd);

        asm.compile_with_num_regs(&mut cb, 1);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov rdi, qword ptr [rbx + 0x10]
        0x4: cmp rdi, 1
        0x8: mov rdi, qword ptr [rbx]
        0xb: mov rdi, rdi
        0xe: mov r10d, 4
        0x14: mov qword ptr [rbp - 8], r10
        0x18: mov r11, qword ptr [rbp - 8]
        0x1c: cmovle rdi, r11
        0x20: mov qword ptr [rbx], rdi
        ");
        assert_snapshot!(cb.hexdump(), @"488b7b104883ff01488b3b4889ff41ba040000004c8955f84c8b5df8490f4efb48893b");
    }

    #[test]
    #[ignore]
    fn test_csel_split() {
        let (mut asm, mut cb) = setup_asm();

        let stack_top = Mem::new(64, SP, 0);
        let elem_opnd = asm.csel_ne(VALUE(0x7f22c88d1930).into(), Qnil.into());
        asm.store(stack_top, elem_opnd);

        asm.compile_with_num_regs(&mut cb, 3);

        assert_disasm_snapshot!(cb.disasm(), @"
            0x0: movabs rax, 0x7f22c88d1930
            0xa: mov ecx, 4
            0xf: cmove rax, rcx
            0x13: mov qword ptr [rbx], rax
        ");
        assert_snapshot!(cb.hexdump(), @"48b830198dc8227f0000b904000000480f44c1488903");
    }

    #[test]
    fn test_mov_m32_imm32() {
        let (mut asm, mut cb) = setup_asm();

        let shape_opnd = Mem::new(32, C_RET_OPND, 0);
        asm.store(shape_opnd, Opnd::UImm(0x8000_0001));
        asm.store(shape_opnd, Opnd::Imm(0x8000_0001));

        asm.compile_with_num_regs(&mut cb, 0);

        assert_disasm_snapshot!(cb.disasm(), @"
            0x0: mov dword ptr [rax], 0x80000001
            0x6: mov dword ptr [rax], 0x80000001
        ");
        assert_snapshot!(cb.hexdump(), @"c70001000080c70001000080");
    }

    #[test]
    fn frame_setup_teardown_preserved_regs() {
        let (mut asm, mut cb) = setup_asm();
        asm.frame_setup(JIT_PRESERVED_REGS);
        asm.frame_teardown(JIT_PRESERVED_REGS);
        asm.cret(C_RET_OPND);
        asm.compile_with_num_regs(&mut cb, 0);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: push rbp
        0x1: mov rbp, rsp
        0x4: push r13
        0x6: push rbx
        0x7: push r12
        0x9: sub rsp, 8
        0xd: mov r13, qword ptr [rbp - 8]
        0x11: mov rbx, qword ptr [rbp - 0x10]
        0x15: mov r12, qword ptr [rbp - 0x18]
        0x19: mov rsp, rbp
        0x1c: pop rbp
        0x1d: ret
        ");
        assert_snapshot!(cb.hexdump(), @"554889e541555341544883ec084c8b6df8488b5df04c8b65e84889ec5dc3");
    }

    #[test]
    fn frame_setup_teardown_stack_base_idx() {
        let (mut asm, mut cb) = setup_asm();
        asm.stack_state.stack_base_idx = 5;
        asm.frame_setup(&[]);
        asm.frame_teardown(&[]);
        asm.compile_with_num_regs(&mut cb, 0);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: push rbp
        0x1: mov rbp, rsp
        0x4: sub rsp, 0x30
        0x8: mov rsp, rbp
        0xb: pop rbp
        ");
        assert_snapshot!(cb.hexdump(), @"554889e54883ec304889ec5d");
    }

    #[test]
    fn test_store_value_without_split() {
        let (mut asm, mut cb) = setup_asm();

        let imitation_heap_value = VALUE(0x1000);
        assert!(imitation_heap_value.heap_object_p());
        asm.store(Mem::new(VALUE_BITS, SP, 0), imitation_heap_value.into());

        asm = asm.x86_scratch_split();
        for name in &asm.label_names {
            cb.new_label(name.to_string());
        }
        let gc_offsets = asm.x86_emit(&mut cb).unwrap();
        assert_eq!(1, gc_offsets.len(), "VALUE source operand should be reported as gc offset");

        assert_disasm_snapshot!(cb.disasm(), @"
            0x0: movabs r11, 0x1000
            0xa: mov qword ptr [rbx], r11
        ");
        assert_snapshot!(cb.hexdump(), @"49bb00100000000000004c891b");
    }

    #[test]
    fn test_csel_split_memory_read() {
        let (mut asm, mut cb) = setup_asm();

        let left = asm.load_mem(Mem::new(64, CFP, 0));
        let right = asm.load_mem(Mem::new(64, CFP, 8));
        let _ = asm.csel_e(left, right);
        asm.compile_with_num_regs(&mut cb, 0);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov r10, qword ptr [r13]
        0x4: mov qword ptr [rbp - 8], r10
        0x8: mov r10, qword ptr [r13 + 8]
        0xc: mov qword ptr [rbp - 0x10], r10
        0x10: mov r11, qword ptr [rbp - 8]
        0x14: mov r10, r11
        0x17: mov qword ptr [rbp - 0x18], r10
        0x1b: mov r11, qword ptr [rbp - 0x10]
        0x1f: mov r10, qword ptr [rbp - 0x18]
        0x23: cmovne r10, r11
        0x27: mov qword ptr [rbp - 0x20], r10
        ");
        assert_snapshot!(cb.hexdump(), @"4d8b55004c8955f84d8b55084c8955f04c8b5df84d89da4c8955e84c8b5df04c8b55e84d0f45d34c8955e0");
    }

    #[test]
    fn test_lea_split_memory_read() {
        let (mut asm, mut cb) = setup_asm();

        let _ = asm.lea(Mem::new(64, CFP, 0));
        asm.compile_with_num_regs(&mut cb, 0);

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: lea r11, [r13]
        0x4: mov qword ptr [rbp - 8], r11
        ");
        assert_snapshot!(cb.hexdump(), @"4d8d5d004c895df8");
    }

    #[test]
    fn test_add_split_two_spilled_inputs() {
        // RAX is safe to be clobbered because it's an output
        // c_ret <- add spill[0], spill[1]
        let lines = split_binop_disasm_lines(BinOpKind::Add, spilled(0), spilled(1), C_RET_OPND);

        assert_snapshot!(lines.join("\n"), @"
        mov r10, qword ptr [rbp - 0x10]
        mov rax, qword ptr [rbp - 8]
        add rax, r10
        ");
    }

    #[test]
    fn test_add_split_spilled_output() {
        // spill[1] <- add cfp, spill[0]
        let lines = split_binop_disasm_lines(BinOpKind::Add, CFP, spilled(0), spilled(1));

        assert_snapshot!(lines.join("\n"), @"
        mov r10, qword ptr [rbp - 8]
        mov r11, r13
        add r11, r10
        mov qword ptr [rbp - 0x10], r11
        ");
    }

    #[test]
    fn test_add_split_reg_spill_spill_when_right_equals_out() {
        // spill[1] <- add cfp, spill[1]
        let lines = split_binop_disasm_lines(BinOpKind::Add, CFP, spilled(1), spilled(1));

        assert_snapshot!(lines.join("\n"), @"
        mov r10, qword ptr [rbp - 0x10]
        mov r11, r13
        add r11, r10
        mov qword ptr [rbp - 0x10], r11
        ");
    }

    #[test]
    fn test_add_split_all_spilled_when_right_equals_out() {
        // spill[1] <- add spill[0], spill[1]
        let mut asm = split_binop(BinOpKind::Add, spilled(0), spilled(1), spilled(1));
        let mut cb = CodeBlock::new_dummy();
        for name in &asm.label_names {
            cb.new_label(name.to_string());
        }
        assert!(asm.x86_emit(&mut cb).is_ok());

        assert_disasm_snapshot!(cb.disasm(), @"
        0x0: mov r10, qword ptr [rbp - 0x10]
        0x4: mov r11, qword ptr [rbp - 8]
        0x8: add r11, r10
        0xb: mov qword ptr [rbp - 0x10], r11
        ");
    }

    #[test]
    fn test_binop_split_matrix() {
        let left_cases = [
            ("reg", CFP),
            ("spill", spilled(0)),
            ("imm32", Opnd::Imm(7)),
            ("imm64", Opnd::UImm(0x1_0000_0000)),
        ];
        let right_cases = [
            ("reg", C_RET_OPND),
            ("spill", spilled(1)),
            ("imm32", Opnd::Imm(9)),
            ("imm64", Opnd::UImm(0x2_0000_0000)),
        ];
        let out_cases = [
            ("out_reg", C_ARG_OPNDS[0]),
            ("out_spill", spilled(2)),
        ];
        let alias_out_cases = [
            ("alias_out_cfp", CFP),
            ("alias_out_reg", C_RET_OPND),
            ("alias_out_spill", spilled(1)),
        ];

        for kind in [BinOpKind::Add, BinOpKind::Sub, BinOpKind::And, BinOpKind::Or, BinOpKind::Xor] {
            for (left_name, left) in left_cases {
                for (right_name, right) in right_cases {
                    for (out_name, out) in out_cases {
                        let case = format!("{left_name}/{right_name}/{out_name}");
                        assert_split_binop_case(kind, left, right, out, &case);
                    }
                }
            }

            for (left_name, left) in left_cases {
                for (alias_name, out) in alias_out_cases {
                    let case = format!("{left_name}/right_eq_out/{alias_name}");
                    assert_split_binop_case(kind, left, out, out, &case);
                }
            }
        }
    }

}
